- .github/workflows/deploy.yml
- .github/workflows/on-pull-request.yml
- README.md
- passageidentity/passage.py
- setup.py
- tests/authenticate_test.py
* `deleteUser()` - delete a Passage user (note that this currently soft deletes the user)
* `createUser()` - accepts a dictionary with `phone` or `email`. Note that if phone is provided, its value must be a valid E164 phone number
* `testCreateAndDeleteUser()`
* Added types for suggestion pop-ups when SDK is being used
* Types are precursor for adding [pydantic](https://pypi.org/project/pydantic/) to give us stronger type checking in the future
NOTE - **In Progress:** adding tests and publishing to CI
> Added User Methods: Create & Delete

- passageidentity/helper.py
- passageidentity/passage.py
- setup.py
- tests/authenticate_test.py
* Add check for Django request
* Add authenticateJWT() 
* bump to 1.1.5
> Django support

- passageidentity/passage.py
- setup.py
> fix typing for python3.7

- passageidentity/passage.py
- setup.py
- tests/authenticate_test.py
- list user devices
- revoke user device
> new device features for passage-python:

- BUILD.md
- passageidentity/helper.py
- passageidentity/passage.py
- setup.py
- tests/authenticate_test.py
- getPublicKey -> fetchApp
- authenticate JWTS using JWKS
- new test to check for JWKS
> [MAIN] JWK Support

- passageidentity/helper.py
- setup.py
Story details: https://app.shortcut.com/passage-identity/story/1346
> feat: [sc-1346] As a python developer, I want the SDK to work for apps that use rest framework requests

- README.md
- passageidentity/passage.py
- setup.py
-   update App fields
-   -required_identifier
-   -require_email_verification
-   +require_identifier_verification
-   add phone_verified to User
This aligns the SDK with the API changes made to simplify identifier verification.
This is a breaking change, as it removes 2 fields.
> sc-1717/update sdks with model changes

- .github/workflows/on-pull-request.yml
- tests/authenticate_test.py
**What type of change is this?**
This is a test cleanup that does not impact SDK functionality. 
**Describe this change**
Update expected backend response on email update to be a lowercase string.
> Chore: Update tests to expect a case insensitive email response

- passageidentity/helper.py
- passageidentity/passage.py
- passageidentity/requests.py
- setup.py
- add sdk version header to all requests
-   reads version from importlib metadata
[Single-sourcing the package version](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/)
> PSG-1036: add sdk version header

- tests/authenticate_test.py
Add more authentication tests: 
- make sure to test invalid JWT case: 
- invalid JWT 
- invalid HEADER 
- invalid COOKIE
> PSG-1301: SDK tests to test both header and cookie auth for all SDKs

- passageidentity/passage.py
- setup.py
Provides the ability to get and configure Auth Fallback App Properties.
> Add Auth Fallback Method Properties

- CHANGELOG.md
- LICENSE
- README.md
- setup.py
Uses repo templates to format README, LICENSE, and remove community files in favour of using organization community files.
**Note:**  the API Reference I left in as both this part and our python docs link to them, this should be taken care of with the rewrite.
Add any other context or screenshots about the pull request here.
> Psg 4898 use repo templates

- .github/workflows/on-pull-request.yml
- .github/workflows/pr-title-check.yml
- .gitignore
- ruff.toml
- adds pr title check to PR CI
- adds linter and formatter to PR CI
- adds default ruff config file
- fixes .gitignore not properly ignoring all pycache directories
> ci: adds linting and formatting jobs to on pull request workflow

- setup.py
-   include dateutil in dependencies
Without this dependency, a consuming app fails with:
```
[2024-12-09 20:38:21 +0000] [18] [ERROR] Exception in worker process
File "/app/app.py", line 3, in <module>
from passageidentity import Passage, PassageError
File "/usr/local/lib/python3.9/site-packages/passageidentity/__init__.py", line 4, in <module>
from .passage import Passage
File "/usr/local/lib/python3.9/site-packages/passageidentity/passage.py", line 9, in <module>
from passageidentity.auth import Auth
File "/usr/local/lib/python3.9/site-packages/passageidentity/auth.py", line 12, in <module>
from passageidentity.openapi_client.api.magic_links_api import MagicLinksApi
File "/usr/local/lib/python3.9/site-packages/passageidentity/openapi_client/__init__.py", line 21, in <module>
from …
```
> fix: add dateutil dependency

- passageidentity/errors.py
This change will make it easier to debug the error with logs.
> chore: add str repr to PassageError class

- passageidentity/passage.py
-   add key existence check & empty value check to argument parsing
-   add `else` branch to argument parsing, to ensure `args` variable is defined in rest of function
> fix: guard against empty params in deprecated magic link method

- passageidentity/passage.py
This ensures the error string between the old and new methods are identical.
> fix: match error raised by new method

- .github/workflows/release.yml
> ci: add failure check for publish step before tagging

- passageidentity/auth.py
- passageidentity/errors.py
- passageidentity/user.py
- tests/errors_test.py
> feat!: remove deprecated PassageError ctor

- README.md
> docs: remove API Refernce table from the README

- .github/workflows/on-pull-request.yml
- setup.py
- removes unused secrets from env vars in CI
- moves pytest env var to be locally scoped to its step
- removes unused dotenv dev dependency
> ci: remove secrets from env vars

- passageidentity/passage.py
adds missing `Passage-Version` header to outgoing requests
> fix: add passage-version header to requests
